### ISSUE TITLE
Is the 19.0.7 release broken on gradle version < 8.8-rc-1

### ISSUE THREAD

**Issue by bjorn-faaberg** [nebula-plugins/nebula-release-plugin#263]
When running builds with 19.0.7 we are getting errors like

```
An exception occurred applying plugin request [id: 'org.jetbrains.kotlin.jvm', version: '1.9.23']
> Failed to apply plugin class 'org.gradle.api.plugins.JavaPlugin'.
   > Could not create domain object 'test' (JvmTestSuite)
```

The release notes for 19.0.7 states the changes in this release is to facilitate Gradly 8.8.
So i tested with the 8.8 release candidate and the build error disapeard.

But I assume this plugin is intended should work with the latest non-release-candate version as well?

**Comment by isivanoff** [comment]
I am having also trouble with gradle version 8.7: 
`* What went wrong:
A problem occurred evaluating root project 'project-name'.
> 'java.util.List org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(java.lang.Object[], groovy.lang.Closure)'
`

**Comment by jimshowalter** [comment]
Same here. 19.0.6 works, 19.0.87 fails, and we can't use RCs.

**Comment by eduardoarantes** [comment]
Same here. 19.0.6 works, 19.0.87 fails

**Comment by schup** [comment]
Upgrade from 19.0.6 to 19.0.7 with gradle 8.7 seems to introduce this error.

Exception:
    
    Caused by: java.lang.NoSuchMethodError: 'java.util.List org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(java.lang.Object[], groovy.lang.Closure)'
	    at nebula.plugin.release.git.command.GitReadOnlyCommandUtil.getTagsPointingAt(GitReadOnlyCommandUtil.groovy:198)
	    at nebula.plugin.release.git.command.GitReadOnlyCommandUtil$getTagsPointingAt$4.call(Unknown Source)
	    at nebula.plugin.release.git.semver.NearestVersionLocator.getLatestTagWithDistance(NearestVersionLocator.groovy:98)
	    at nebula.plugin.release.git.semver.NearestVersionLocator.locate(NearestVersionLocator.groovy:78)
	    at nebula.plugin.release.git.semver.NearestVersionLocator$locate.call(Unknown Source)
	    at nebula.plugin.release.git.semver.SemVerStrategy.doInfer(SemVerStrategy.groovy:157)

**Comment by bjorn-faaberg** [comment]
I will close my issue since  19.0.8 sets distributionUrl to gradle 8.7
